# Generated by Django 4.1.2 on 2022-10-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('lname', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('password', models.CharField(max_length=255)),
                ('pharma_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.TextField()),
                ('willaya', models.CharField(blank=True, max_length=255, null=True)),
                ('employees', models.IntegerField()),
            ],
        ),
    ]
