# Generated by Django 4.1.2 on 2022-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaApp', '0002_pharmacylocation_delete_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacylocation',
            name='pharmaName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
